### ISSUE TITLE
Application RUNS* from a docker file

### ISSUE THREAD

**Issue by lgartrell** [YCPRadioTelescope/RT-Contracts#73]
## Requirements
- [x] Complete understanding of current deployment strategy, and knowledge of how the front end, control room, and back end all work together 
- [x] Prerequisite knowledge of docker, and how to structure efficient containers
- [x] Completely working backend environment with knowledge of common stumbling points

## Brief Overview
This task relates to the first part of our deployment strategy, which is containerizing our application. For this to work, ~~essentially all the work that needs to be done is to set up the back-end environment in a dockerfile, very similar to what we have already been working on (which was just getting set up on our workspaces).~~

With new learning, comes new understanding. After understanding our deployment, we bundle the backend into a .jar file. So, the work is to figure out how to **run** the .jar in a container, rather than to build it.

## Possible Plan
1. ~~Create dependency list regarding to the back-end environment~~
1. ~~Research docker images relating to the tools we use~~
    1. ~~Docker base image for open jdk 8~~
    1. Docker base image for Gradle 4.7 **(maybe not needed)**
    1. etc. for each tool used
1. Create dockerfile
1. Test and refine dockerfile to reduce size of containers
1. **Repeat** step 4 until size is acceptable

## Further Learning
General docker documentation: https://docs.docker.com/ 
Dockerfile documentation: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Comment by TUllery** [comment]
An epic change needs epic description. Describe in detail please. You can augment with links that describe the functionality.

**Comment by lgartrell** [comment]
Talked with Joel, learned that we deploy a single .jar file to AWS. No longer need to build to run all of our dependencies, should be just to build to run our .jar file. More learning needs to be done on what that entails, but I found an article [here](https://medium.com/@wkrzywiec/how-to-put-your-java-application-into-docker-container-5e0a02acdd6b) that looks like exactly what we need. Will be following it and sending a new comment with the result

**Comment by lgartrell** [comment]
## Update
got the image I think is sufficient, but ran into my first roadblock which is managing two different "local hosts". Docker has it's own localhost, which is isolated in it's container environment. I found a work around which is changing the IP table and mapping docker to something, but I need more digging into it.

This would not be a problem when we are actually deployed, but for local testing it is! More updates coming
